version: "2.1"

services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: .
      dockerfile: .docker/nginx.dockerfile
    environment:
      NODE_ENV: production
    # volumes:
    #   - ./ng-app/dist:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

  node:
    container_name: nodeapp
    image: nodeapp
    build:
      context: ./microservices/node-api
      dockerfile: .docker/node.production.dockerfile
    # volumes:
    #   - ./microservices/node-api:/var/www/angularnoderestfulservice
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - app-network

  #No authentication is provided here - JUST A DEMO! That would absolutely
  #be needed for a "real" application
  mongodb:
    container_name: mongodb
    image: mongo
    networks:
      - app-network

  # cadvisor:
  #   container_name: cadvisor
  #   image: google/cadvisor
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
