version: "3.1"

services:
  nginx:
    container_name: optradek/points-manager:nginx-1.0.2
    image: optradek/points-manager:nginx-1.0.2
    build:
      context: .
      dockerfile: .docker/nginx.dockerfile
    environment:
      NODE_ENV: production
    # volumes:
    #   - ./ng-app/dist:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

  node:
    container_name: optradek/points-manager:nodeapp-1.0.2
    image: optradek/points-manager:nodeapp-1.0.2
    build:
      context: ./microservices/node-api
      dockerfile: .docker/node.production.dockerfile
    # volumes:
    #   - ./microservices/node-api:/var/www/angularnoderestfulservice
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
